AWS/config/config-delivery-channel/config.tf
AWS/config/config-recorder-status/config.tf
AWS/config/config-recorder/config.tf
AWS/config/config-recorder/outputs.tf
AWS/ebs-volume/ebs.tf
AWS/ebs-volume/outputs.tf
AWS/ec2-ebs/ec2.tf
AWS/ec2-ebs/outputs.tf
AWS/ec2-eip/ec2.tf
AWS/ec2-eip/eip.tf
AWS/ec2-eip/outputs.tf
AWS/inspector/cloudwatch.tf
AWS/inspector/iam.tf
AWS/inspector/main.tf
AWS/rds-sql-server/outputs.tf
AWS/rds-sql-server/rds.tf
AWS/vpc-flow-logs/vpc-flow-log/cloudwatch.tf
AWS/vpc-flow-logs/vpc-flow-log/vpc-flow-logs.tf
AWS/vpc-flow-logs/vpc-flow-logs-iam-role/iam-role.tf
AWS/vpc-flow-logs/vpc-flow-logs-iam-role/outputs.tf
AWS/vpc-third-parties/vpc-customer-gateway/customer-gateway.tf
AWS/vpc-third-parties/vpc-customer-gateway/outputs.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/internet-gateway.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/outputs.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/routing.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/subnets.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/vpc.tf
AWS/vpc-third-parties/vpc-with-igw-vpn/vpn.tf

Clean up interpolation issues after terraform upgrade

---

AWS/iam-instance-roles/commvault-iam-service-role/outputs.tf
AWS/iam-instance-roles/wt-standard-instance-role-rds-s3/main.tf
AWS/iam-instance-roles/wt-standard-instance-role-rds-s3/outputs.tf
AWS/iam-instance-roles/wt-standard-instance-role-s3/main.tf
AWS/iam-instance-roles/wt-standard-instance-role-s3/outputs.tf
AWS/iam-instance-roles/wt-standard-instance-role/main.tf
AWS/iam-instance-roles/wt-standard-instance-role/outputs.tf

❤️ Testing the modules
⭐️ Realised I needed another output
🌕 Had the Role reference in two places

only thing with modules is you need to test

---

AWS/iam-instance-roles/wt-standard-instance-role/main.tf

Testing again, Not sure I need the policy and the policy attachment when using OOB AWS Modules.

dont need both policy and attachment

---

AWS/iam-instance-roles/commvault-iam-service-role/main.tf
AWS/iam-instance-roles/commvault-iam-service-role/variables.tf
AWS/iam-instance-roles/wt-standard-instance-role-rds-s3/main.tf
AWS/iam-instance-roles/wt-standard-instance-role-rds-s3/variables.tf
AWS/iam-instance-roles/wt-standard-instance-role-s3/main.tf
AWS/iam-instance-roles/wt-standard-instance-role-s3/variables.tf
AWS/iam-instance-roles/wt-standard-instance-role/main.tf
AWS/iam-instance-roles/wt-standard-instance-role/variables.tf
AWS/inspector/iam.tf
AWS/inspector/variables.tf

🔥 Nothing to apply 🔥 
🎀 Updated the Inspector and IAM Instance Role modules with the new Tags.  
🎶 To pull these into each repo you need to delete your .terraform folder and then run plan.sh which runs a get and am init

Update the Role and the inspector modules with the new tags

---

AWS/iam-user/commvault-iam-user/policies/commvault-iam-user.json

added iam:SimulatePrincipalPolicy as per CHG0032706

commvault iam change

---

AWS/iam-user/commvault-rds-iam-user/iam-group.tf
AWS/iam-user/commvault-rds-iam-user/iam-policy.tf
AWS/iam-user/commvault-rds-iam-user/iam-user.tf
AWS/iam-user/commvault-rds-iam-user/policies/commvault-rds-iam-user.json
AWS/iam-user/commvault-rds-iam-user/variables.tf

https://wellcome.service-now.com/nav_to.do?uri=change_request.do?sys_id=428040911b7d155036160e51f54bcbf7

New Commvault User for RDS privs

---

AWS/iam-user/commvault-rds-iam-user/policies/commvault-rds-iam-user.json

added "ec2:DescribeInstanceTypes" & "ec2:DescribeInstanceTypeOfferings"

added ec2 describe privs

---

AWS/vpc-flow-logs/vpc-flow-log/cloudwatch.tf
AWS/vpc-flow-logs/vpc-flow-log/variables.tf
AWS/vpc-flow-logs/vpc-flow-logs-iam-role/iam-role.tf
AWS/vpc-flow-logs/vpc-flow-logs-iam-role/variables.tf

> Please provide a title for the pull request.
>Include when you plan to deploy this pull request
>Provide a description of what this pull request is doing. This should be in plain business language with any acronyms defined. Consider that the audience may not be experts in your field such as  auditors or senior management.
> Provide the reason why the amendment is required. eg New service, fix something or decommission.  Ensure that if there are regulatory, cost, legal, security or support reasons that this is highlighted here.
___
>Please insert any reference numbers to outside applications i.e. Change Request or Incident number from Service Now, MCOM reference number
>Provide a link to the change / MCOM item
---
> List the steps in order of completion that will be worked through when …

4370909297-vpc-flow-logs-and-config

---

AWS/vpc-flow-logs-iam-role/main.tf

> Please provide a title for the pull request.
>Include when you plan to deploy this pull request
>Provide a description of what this pull request is doing. This should be in plain business language with any acronyms defined. Consider that the audience may not be experts in your field such as  auditors or senior management.
> Provide the reason why the amendment is required. eg New service, fix something or decommission.  Ensure that if there are regulatory, cost, legal, security or support reasons that this is highlighted here.
___
>Please insert any reference numbers to outside applications i.e. Change Request or Incident number from Service Now, MCOM reference number
>Provide a link to the change / MCOM item
---
> List the steps in order of completion that will be worked through when …

Policy does not support tags!

---

AWS/iam-roles/ta-iam-role/main.tf
AWS/iam-roles/ta-iam-role/policies/wt-ta-policy.json

Additional permission for ThreatAware role in AWS
Applied
Provide ssm:DescribeInstanceInformation permission to ThreatAware role in AWS.
It is required in order to obtain all instance info as per ThreatAware new SSM integration.
___
[CHG0034394](https://wellcome.service-now.com/nav_to.do?uri=change_request.do?sys_id=935244311b33a95061294333b24bcb13)
---
Applied via Terraform.
Complementing read-only permission.
Applying the change to the individual AWS accounts and check the results.
---
N/A

CHG0034394-ta-role-ssm-policy

---

AWS/iam-roles/ta-iam-role/policies/wt-ta-policy.json

Syntax correction
N/A
Correct the syntax in the JSON file by removing the dash symbol.
Required for the policy to work
___
CHG0034394
---
N/A
N/A
N/A
---
N/A

CHG0034394-ta-role-ssm-policy-fix

---

AWS/iam-roles/lm-iam-roles/main.tf

Can't quite get the template to resolve!

4942049683-lm-iam-module-adding-path

---

AWS/lm-log-forwarder/main.tf
AWS/lm-log-forwarder/variables.tf

4942960889-lambda-log-forwarder
🌴 Applied 🌴 
Create a module for implementing the LM Log Forwarder
To Deploy Log forwarder for LM Implementation.
___
4942960889-lambda-log-forwarder
---
🌴 Applied 🌴 
New Module
Once Merged Test implementation in Sandpit
---
[Replace with link name](https://)

4942960889-lambda-log-forwarder

---

AWS/iam-instance-roles/commvault-iam-service-role/main.tf

Adding SSM policy to Commvault instace role
N/a
Adding the SSM policies that the standard profile have to the Commvault instance profile
Required so that SSM works on the Commvault servers
___
CHG0034456
CHG0034456
---
> List the steps in order of completion that will be worked through when implementing this pull request. Be specific if you are creating or changing  objects eg. an Ec2 instance, RDS, code or form, state the name and location. <br><br>
> If the work is divided amongst multiple resources state who will carry out which step and if there are any dependencies on steps.
>*Optional field if you would like to add any analysis not captured in the risk assessment.
>Describe the steps you will take to revert the pull request to its pre-implementation state. Be specific, if particular …

CHG0034456 - update commvault instance profile

---

AWS/LM/lm-aws-account-onboarding-role/variables.tf
AWS/LM/lm-log-forwarder/README.md
AWS/LM/lm-log-forwarder/variables.tf

sensitive values

---

AWS/iam-user/commvault-iam-user/policies/commvault-iam-user.json

Add S3RestoreObject to CommvaultBackup user
N/A
Add the "s3:RestoreObject" permission to the policy attached to "CommvaultBackup" user
Required for the restore operations to work.
___
INC0051534
---
N/A
---
N/A

INC0051534-cvault-iam-s3restoreobject

---

AWS/LM/lm-log-forwarder/files/latest.yaml
AWS/LM/lm-log-forwarder/main.tf

Kate testing something out in Dev.  Will revert this if its not right!

log-retention-for-LM-log-forwarders

---

AWS/LM/lm-log-forwarder/main.tf

Kate Again. will remove if doesn't work

adding the variable to the module

---

AWS/LM/lm-log-forwarder/files/latest.yaml
AWS/LM/lm-log-forwarder/main.tf

kate-test-forwarder

---

AWS/iam-instance-roles/wt-panorama-instance-role/main.tf
AWS/iam-instance-roles/wt-panorama-instance-role/outputs.tf
AWS/iam-instance-roles/wt-panorama-instance-role/policies/ec2-trust.json
AWS/iam-instance-roles/wt-panorama-instance-role/variables.tf

Instance role for Panorama
N/A
New instance role with the addition of EC2 readonly access for Panorama servers.
Panorama servers require the additional permission for the Panorama VM monitoring plugin
___
[CHG0034933](https://wellcome.service-now.com/nav_to.do?uri=change_request.do?sys_id=01a7f0131b2b7d9036160e51f54bcbfc)
---
This piece of Terraform code comes from the standard instance role and then has been edited for the scope.
No risks. Additional read-only permission to the already existing permissions.
The Panorama plugin will be tested.
---
[IAM Instance Role](https://wellcometrust.atlassian.net/wiki/spaces/INF/pages/916160538/IAM+Instance+Roles)

CHG0034933-panorama-instance-role

---

AWS/iam-instance-roles/wt-panorama-cross-instance-role/main.tf
AWS/iam-instance-roles/wt-panorama-cross-instance-role/variables.tf
AWS/iam-instance-roles/wt-panorama-instance-role/main.tf
AWS/iam-instance-roles/wt-panorama-instance-role/variables.tf

Fix variables for Panorama roles
N/A
Corrected the variables in the Panorama roles by using the standard instance role modules as reference.
The Panorama instance roles didn't have the variables set correctly.
___
N/A
---
N/A
None
N/A
---
N/A

panorama-fix-variables

---

AWS/iam-instance-roles/wt-panorama-instance-role/policies/wt-panorama-policy.json

Correcting wrong Panorama role name
Applied
Correcting the cross-account role name from WT_Panorama_Instance_Role to WT_Panorama_Cross_Account_Instance_Role
The name for the cross-account role was not written correctly. It was pointing to a non-existing role.
___
[CHG0034960](https://wellcome.service-now.com/nav_to.do?uri=change_request.do?sys_id=4b0bee451b333150c4d2a860f54bcb99)
---
N/A
None
Sunny will test on Panorama.
---
N/A

CHG0034960-panorama-fix-policy

---

AWS/iam-instance-roles/wt-panorama-cross-instance-role/main.tf

Remove instance profile from Panorama cross-account role
N/A
Removing the instance profile section of the Panorama cross-account role
Resolving the issue of letting Panorama from NCW Prod assume the role in other AWS accounts.
___
CHG0034960
---
Updating module, then deploying in NCW Dev for testing.
None. The role doesn't seem to be working yet.
Checking with Sunny.
---
N/A

CHG0034960-panorama-cross-account-role-fix

---

AWS/iam-instance-roles/wt-panorama-cross-instance-role/main.tf

Reverts wellcometrust/ncw-terraform-modules#76
Putting the Instance profile back in place for further testing!

Revert "CHG0034960-panorama-cross-account-role-fix"

---

pull_request_template.md

New Pull Request template (2024-02)
N/A
Edited the existing Pull Request template in order to make it more efficient: the most common options are already selected.
In addition typo corrected, blank lines removed, extra lines for references removed.
Making the template shorter and faster in most common scenarios.
___
N/A
---
N/A
N/A
N/A
---
N/A

pull-request-template-2024_02

---

AWS/iam-instance-roles/commvault-iam-service-role/policies/commvault.json

Add ec2:DescribeVpcAttribute to Commvault role
N/A
Add the IAM permissions "ec2:DescribeVpcAttribute" to the Commvault role
Required for Commvault
___
CHG0035422
---
N/A
Read-only permission
Revert Pull Request
N/A
---
N/A

cv-policy-ec2vpcattr
